export default {
  GET_PRESTACIONES: 'GET_PRESTACIONES',
  GET_SELECTED_PRESTACION: 'GET_SELECTED_PRESTACION',
  GET_ETAPAS: 'GET_ETAPAS',
  GET_BENEFICIARY_TYPE: 'GET_BENEFICIARY_TYPE',
  GET_TYPE: 'GET_TYPE'
}
